# Generated by Django 4.2.9 on 2024-01-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_review_unique_user_product_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='commentary',
            field=models.TextField(blank=True),
        ),
    ]
