# Generated by Django 4.2.9 on 2024-01-18 16:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0004_alter_review_commentary'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_user_product_review',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'product')},
        ),
    ]
