# Generated by Django 4.2.9 on 2024-01-10 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='surname',
            new_name='sdfsdf',
        ),
    ]
