# Generated by Django 4.2.9 on 2024-01-10 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_surname_user_sdfsdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='sdfsdf',
            new_name='surname',
        ),
    ]
